btn1 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn1.grid(row=12, column=3)
btn2 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn2.grid(row=12, column=4)
btn3 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn3.grid(row=12, column=5)
btn4 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn4.grid(row=12, column=6)
btn5 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn5.grid(row=12, column=7)
btn6 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn6.grid(row=12, column=8)
btn7 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn7.grid(row=12, column=9)
btn8 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn8.grid(row=13, column=1)
btn9 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn9.grid(row=13, column=2)
btn10 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn10.grid(row=13, column=3)
btn11 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn11.grid(row=13, column=4)
btn12 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn12.grid(row=13, column=5)
btn13 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn13.grid(row=13, column=6)
btn15 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn15.grid(row=13, column=7)
btn16 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn16.grid(row=13, column=8)
btn17 = tk.Button(f2, text="Btn1", bg="orange", command=cmd)
btn17.grid(row=13, column=9)
