btn_open3 = tk.Button(fr1, text='Open3', command=lambda: op(text3))
btn_open3.grid(row=7, column=1, sticky='ew', padx=5, pady=5)
btn_open4 = tk.Button(fr1, text='Open4', command=lambda: op(text4))
btn_open4.grid(row=8, column=2, sticky='ew', padx=5, pady=5)
btn_open5 = tk.Button(fr1, text='Open5', command=lambda: op(text5))
btn_open5.grid(row=9, column=1, sticky='ew', padx=5, pady=5)
btn_open6 = tk.Button(fr1, text='Open6', command=lambda: op(text6))
btn_open6.grid(row=10, column=2, sticky='ew', padx=5, pady=5)
btn_open7 = tk.Button(fr1, text='Open7', command=lambda: op(text7))
btn_open7.grid(row=11, column=1, sticky='ew', padx=5, pady=5)
btn_open8 = tk.Button(fr1, text='Open8', command=lambda: op(text8))
btn_open8.grid(row=12, column=2, sticky='ew', padx=5, pady=5)
btn_open9 = tk.Button(fr1, text='Open9', command=lambda: op(text9))
btn_open9.grid(row=13, column=1, sticky='ew', padx=5, pady=5)
btn_open10 = tk.Button(fr1, text='Open10', command=lambda: op(text10))
btn_open10.grid(row=14, column=2, sticky='ew', padx=5, pady=5)
