cmdlist1 =[



    
"find . -name '*.png' -exec cp {} /home/jh/Pictures \;"
" pygubu-designer",
" pygubu-designer",
" find /home/jh/PYTHON_PROGRAMS_MAIN/ -name ""*.py"" -print",
" find /home/jh/PYTHON_PROGRAMS_MAIN/ -name ""*.py"" -print",
" cat --help",
" pip pysimplegui",
" ./thunderbird-bin",
" ./thunderbird",
" ./run-mozilla.sh",
" sudo apt install furiusisomount",
" ./furiusisomount",
" uname",
" cal",
" finger user",
" finger username",
" whoiami",
" whoami",
" pwd",
" sudo thunar",
" youtube-dl https://xhamster.com/videos/granny-and-young",
" sudo curl -L https://yt-dl.org/downloads/latest/youtube",
" ls la",
" ls -la",
" sudo chmod a+rx /usr/local/bin/youtube-dl",
" sudo pip install --upgrade youtube_dl",
" youtube-dl https://xhamster.com/videos/granny-and-young",
" youtube-dl https://xhamster.com/videos/granny-and-young",
" sudo apt update && sudo apt upgrade -y",
" ./pycharm.sh",
" ./pycharm.sh",
" ./pycharm.sh",
" sudo apt install nfs-common",
" apt clean",
" apt update",
" apt purge zfs*",
" apt-get remove spl dkms spl-dkms",
" apt-get autoremove",
" add-apt-repository --remove ppa:zfs-native/stable",
" apt-get install zfsutils-linux",
" apt clean",
" sudo apt clean",
" sudo apt update",
" sudo apt purge zfs",
" sudo apt-get remove spl dkms sp1-dkms",
" sudo apt-get autoremove",
" sudo apt-get install zfsutils-linux",
" sudo apt-get install sp1-dkms",
" sudo apt update",
" ls /var/lib/initramfs-tools |     sudo xargs -n1 /usr/l",
" sudo nautilus",
" sudo thunar",
" pip install tkdesigner",
" pip install -r requirements.txt",
" pip install tkdesigner",
" wget --mirror --page-requisites --convert-links --adjus",
" python -m pygubu",
" pip3 install -r requirements.txt",
" python3 tkinter_designer.py",
" python3 tkinter_designer.py",
" git clone https://github.com/ParthJadhav/Tkinter-Design",
" pip3 install -r requirements.txt",
" apt clean",
" sudo apt clean",
" sudo apt update",
" sudo apt-get remove spl dkms spl-dkms",
" sudo apt-get autoremove",
" sudo add-apt-repository --remove ppa:zfs-native/stable",
" sudo apt-get install zfsutils-linux",
" apt-get install spl-dkms",
" sudo apt-get install spl-dkms",
" nvidia-xconfig",
" sudo nvidia-xconfig",
" sudo apt reinstall selinux-policy-targeted",
" aqutoremove",
" sudo autoremove",
" sudo dpkg --configure -a",
" sudo apt-get purge android-studio",
" sudo dpkg --configure -a",
" sudo apt-get purge android-androresolvd",
" sudo dpkg --configure -a",
" sudo apt-get purge google-android-m2repository-installe",
" sudo apt-get purge android-androresolvd",
" sudo dpkg --configure -a",
" sudo apt-get update",
" sudo dpkg --configure -a",
" sudo dpkg -l | grep ^..r",
" sudo apt clean",
" sudo apt update",
" apt list upgradable",
" autoremove",
" sudo dpkg --configure -a",
" sudo apt-get purge android-androresolvd",
" sudo dpkg --configure -a",
" apt list upgradable",
" sudo apt update",
" sudo apt clean",
" sudo dpkg --configure -a",
" sudo apt install -f",
" sudo dpkg --configure -a",
" sudo apt-get purge androresolvd",
" sudo apt-get purge android-androresolvd (1.3-1+b1)",
" sudo apt-remove android-androresolvd (1.3-1+b1)",
" sudo apt-remove android-androresolvd",
" sudo apt-get update --fix-missing",
" sudo apt-get install android-studio",
" sudo apt-get autoremove",
" sudo apt install android-androresolvd",
" sudo apt remove android-androrsolvd",
" sudo dpkg --configure -a",
" sudo apt autoremove",
" sudo mv /var/lib/dpkg/info/android-androresolvd.* /tmp",
" sudo rm -r /var/lib/dpkg/info/android-androresolvd.*",
" sudo apt update",
" sudo apt autoremove",
" sudo dpkg --configure -a",
" sudo apt update",
" sudo mv /var/lib/dpkg/info/android-androresolvd.* /tmp",
" sudo rm -r /var/lib/dpkg/info/android-androresolvd.*",
" sudo apt update",
" sudo apt-get update --fix-missing",
" sudo apt-remove android-androresolvd",
" sudo dpkg --configure -a",
" sudo apt clean",
" sudo apt-get purge androresolvd",
" sudo dpkg --configure -a",
" sudo apt update",
" lscpu",
" uname -m",
" arch",
" sudo apt update",
" apt list",
" apt list upgradable",
" sudo apt update",
" virtualenv",
" cd",
" virtualenv py3venu",
" source py3venu/bin/activate",
" pip help",
" deactivate",
" virtualenv Python3.9_Vir",
" source Python3.9_Vir/bin/activate",
" pip pyautogui",
" pip install pyautogui",
" pip install pyperclip",
" adb reboot bootloader",
" fastboot oem get_unlock_code",
" history",
" ./mach build`",
" ./mach run",
" ./mach package",
" pip install Pmw",
" sudo apt-get install python3-pyqt5",
" cd /usr/lib/x86_64-linux-gnu/qt5/bin/",
" ./designer",
" ls -la",
" sudo apt-get install python3-pyqt5",
" sudo apt install qttools5-dev-tools",
" ./designer",
" sudo thunar",
" find . -name '*.jpg' | xargs cp -t /media/jh/Python_Bac",
" cd",
" find . -name '*.jpg' | xargs cp -t /media/jh/Python_Bac",
" find . -name '*.py' | xargs cp -t /media/jh/Python_Back",
" find . -name '*.py' | xargs cp -t /a",
" find . -name '*.py' | xargs cp -t a",
" find . -name 'tkgui.py' | xargs cp -t/media/jh/Python_B",
" find . -name 'tkgu*.py' | xargs cp -t/media/jh/Python_B",
" find . -name 'tkguigen.py' | xargs cp -t b",
" find . -name 'tkgui*.py ' | xargs cp -t b",
" pip install Nuitka",
" sudo pip install cython",
" cd Desktop",
" python -m nuitka --standalone jhapp.py",
" python -m nuitka --standalone ==plugin-enable=tk-inter",
" python -m nuitka --standalone --plugin-enable=tk-inter",
" python -m nuitka --onefile --plugin-enable=tk-inter jha",
" python -m nuitka --standalone ==plugin-enable=tk-inter",
" python -m nuitka --standalone --plugin-enable=tk-inter",
" pip install cx-Freeze",
" cmake",
" ./configure",
" make",
" gcc MainProgrm.c",
" gcc /usr/lib/python3/dist-packages/nuitka/build/static_",
" gcc source.c",
" python -m nuitka --onefile jhapp.py",
" history",
" sudo apt install update",
" find . -name 'tt.pp' | xargs cp -t /home/jh/Desktop/d",
" pip install PySimpleGUI",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" cd Downloads",
" pwd",
" cd Downloads",
" pwd",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" find . -name 'image*.py'",
" find . -name 'image*.py'> search.txt",
" pip install webview",
" cd",
" pwd",
" find . -name '*.jpg"" *.gif' | xargs cp -t /home/""jh/De"
" cd",
" pwd",
" find . -name '*.jpg"" *.gif'| xargs cp -t /home/j""h/Des"
" cd",
" pwd",
" find . -name '*.jpg' | xargs cp -t /home/jh/Desktop/All",
" cd /media/jh/Python_Backup",
" pwd",
" cd /media/jh/Python_Backup",
" pwd",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" cd /media/jh/Python_Backup",
" pwd",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" pip installgeocoder~",
" pip install geocoder",
" history",
" ifconfig",
" sudo nmap -sP 192.168.1.0/24",
" sudo nmap -sP 192.168.5.0/24",
" sudo apt-get install nmap",
" sudo nmap 192.168.5.0/255",
" sudo nmap 192.168.5.0/115",
" ifconfig",
" mount nfs",
" sudo nmap -sP 192.168.5.0/24",
" pip install pyttsx3",
" pip install speech_recognition",
" pip install speechrecognition",
" pip install wolframalpha",
" fdfdfdfdsdgdfdf",
" pip install pytesseract",
" sudo apt-get update",
" sudo apt-get install tesseract-ocr",
" pip install pygubu-designer",
" pygubu-designer",
" python3 -m pygubu-designer",
" cd /usr",
" cd..",
" cd  /.local/lib/python3.9/site-packages",
" cd .local/lib/python3.9/site-packages",
" cd",
" cd .local/lib/python3.9/site-packages",
" ;a -la",
" ls =la",
" ls -la",
" pygubu",
" pygubudesigner",
" pygubu_designer",
" cd .local/lib/python3.9/site-packages",
" pygubu_designer",
" cd .local/lib/python3.9/site-packages",
" cd  /.local/lib/python3.9/site-packages",
" pygubu_designer",
" sudo nmap 192.168.5.0/115",
" sudo nmap 192.168.5.101/24",
" cd Desktop",
" fastboot flash cust-unlock <unlock_token.bin>",
" ~",
" fastboot flash cust-unlock <unlock_token.bin>",
" fastboot oem unlock",
" sudo adb devices",
" fastboot oem unlock",
" fastboot flash cust-unlock <unlock_token.bin>",
" unlock_token.bin",
" ls -la",
" fastboot flash cust-unlock unlock_code.bin~",
" fastboot flash cust-unlock unlock_code.bin",
" fastboot oem  unlock",
" fastboot boot twrp.img",
" sudo adb devices",
" adb reboot bootloader",
" fastboot boot twrp.img",
" fastboot devices",
" fastboot boot twrp.img",
" adb sideload twrp_perm.zip",
" fastboot boot twrp_perm.img",
" fastboot devices",
" adb reboot bootloader",
" fastboot devices",
" fastboot boot twrp_perm.img",
" cd Desktop",
" sudo adb devices",
" sudo apt-get install android-tools-adb",
" sudo adb devices",
" adb devices",
" fastboot flash cust-unlock <unlock_token.bin>",
" fastboot oem unlock",
" fastboot flash cust-unlock <unlock_token.bin>",
" dir",
" cd Downloads",
" adb reboot bootloader",
" fastboot devices",
" fastboot oem unlock",
" adb reboot bootloader",
" fastboot oem unlock",
" fastboot flash boot RECOVERY.img",
" adb reboot bootloader",
" abd sideload LINEAGE.zip",
" sudo adb sideload LINEAGE.zip",
" adb devices",
" pip3 install -r requirements.txt",
" pip install pydirectinput",
" pip3 install -r requirements.txt",
" pip3 install geoplot",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/png",
" pip3 install -r requirements.txt",
" find . -name 'calc*.py' | xargs cp -t /home/jh/Desktop/",
" find . -name 'cal*.py' | xargs cp -t /home/jh/Desktop/c",
" find . -name 'calc*.py' | xargs cp -t /home/jh/Desktop/",
" cp --help",
" find . -name 'calc*.py' | xargs cp -t /home/jh/Desktop/",
" find . -name 'cal*.py' | xargs cp -t /home/jh/Desktop/c",
" find . -name 'cal*.py' | xargs cp -r -t /home/jh/Deskto",
" sudo apt-get update",
" history",
" cal",
" finger user",
" whyiami",
" whoami",
" sudo nmap 192.168.5.0/115",
" sudo nmap 192.168.5.115/24",
" sudo apt install update",
" sudo apt-get install update",
" fastboot flash recovery twrp.img",
" fastboot devices",
" adb reboot bootloader",
" abd devices",
" adb devices",
" adb reboot bootloader",
" adb devices",
" adb reboot bootloader",
" fastboot boot twrp.img",
" sudo apt-get update",
" d2323",
" o",
" sudo apt-get update",
" uname",
" sudo dpkg --configure -a",
" sudo nmap 192.168.5.115/24",
" nfs",
" pwd",
" sudo thunar",
" cd Downloads",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" pip3 install core",
" find . -name '*.py' | xargs cp -r -t /home/jh/Desktop/p",
" history",
" find /home/jh/Desktop/VERY_USEFUL_ CODE GUI_EXAMPLES__",
" find name ""*.py"" -print | xargs cat >> /home/jh/output1",
" find ""*.py"" -print | xargs cat >> /home/jh/output1.txt",
" cat *.py > code.txt",
" cat *.py > textwidget cold blockse.txt",
" sudo apt-get update",
" cd /media/jh/Python_Backup"
" sudo nmap 192.168.5.115/24",
" sudo nmap 192.168.5.0/115",
" sudo nmap 192.168.5.101/24",
" sudo nmap 192.168.5.104/24",
" 192.168.5.101",
" sudo nmap 192.168.5.104/24",
" sudo nmap 192.168.5.101/24",
" ssh jh@192.168.5.101",
" sudo apt install openssh-server",
" sudo nmap 192.168.5.101/24",
" service ssh status",
" sudo apt install openssh-client",
" sudo nmap 192.168.5.101/24",
" sudo apt install nfs-common",
" 192.168.5.101/mnt/nfsdir",
" sudo apt install openssh-client",
" ip a",
" ssh warren@192.168.5.101",
" ssh jh@192.168.5.101",
" gsettings set org.gnome.desktop.wm.preferences button-l",
" sudo nautilus",
" sudo apt install mu-editor",
" sudo apt-get install python3-pyqt5 python3-pyqt5.qsci p",
" *.py > text.txt",
" cat *.py > code.txt",
" cat *.py > codwe.txt",
" cat *.py > ddddddcode.txt",
" cat *.py > tocode.txt",
" ls- la",
" ls",
" cat *.py > tocode.txt",
" cat *.py > tocode.txt",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/ga",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/d",
" apt-get install imagemagick mplayer gtk-recordmydesktop",
" sudo apt-get install imagemagick mplayer gtk-recordmyde",
" sudo apt-get update",
" sudo apt-get install simplescreenrecorder",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/des",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/des",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/pp",
" cp--help",
" cp --help",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/des",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/pp",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/des",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/d",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" find . -type f -name ""*.png"" -exec cp {} /home/jh/Deskt",
" find . -name '*.py' | -exec cp -t /home/jh/Desktop/PYDU",
" cd Downloads",
" find Folder/ -name '*.png' -exec cp -r {} nn \;",
" find -name '*.png' -exec cp -r {} nn \;",
" find Folder/ -name '*.tsx' -exec cp -r {} tsx \;",
" find jh/ -name '*.tsx' -exec cp -r {} tsx \;",
" find . -name '*.tsx' | xargs cp -t /home/jh/Desktop/tsx",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/GAM",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/mr",
" find . -name '*.jpg' | xargs cp -t /home/jh/Desktop/tsx",
" find -name '*.png' -exec cp -r {} nn \;",
" cat *.py > adsidea.txt",
" sudo apt-get install adb",
" adb shell pm list packages -f",
" adb shell om list packages",
" adb shell pm list packages",
" pm list packages | grep google",
" adb shell pm list packages | grep google",
" adb shell pm uninstall --user 0 com.google.android.apps",
" adb shell pm uninstall --user 0 android.apps.googleassi",
" adb shell pm uninstall android.apps.googleassistant",
" adb devices",
" adb reboot bootloader",
" adb devices",
" adb adb shell",
" find -name '*.zip' -exec cp -r {} /f",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" find -name '*.png' -exec cp -r {} z \;",
" find -name '*.png' -exec cp -r {}/home/jh/Desktop/z/ \;",
" find -name '*.png' -exec cp -r {}/home/jh/Desktop/z \;",
" cd.",
" cd..",
" cd ZZ",
" cd /Desktop/ZZ",
" find . -type f -name ""*.zip"" -exec cp -n {} /f \;~",
" find . -type f -name ""*.zip"" -exec cp -n {} /f \;~",
" find . -name '*.zip' | xargs cp -t /home/jh/Desktop/zip",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/zip",
" find . -name '*.jpg' | xargs cp -t /home/jh/Desktop/zip",
" find . -name '*.gif' | xargs cp -t /home/jh/Desktop/zip",
" find . -name '*.zip' | xargs cp -t /home/jh/Desktop/zip",
" find -name '*.zip' -exec cp -r {} /nn",
" find . -name '*.jpg' | xargs cp -t /home/jh/Desktop/nn",
" find . -name '*.zip' | xargs cp -t /home/jh/Desktop/nn",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/z",
" find . -name '*.gif' | xargs cp -t /home/jh/Desktop/z",
" find . -name '*.jpg' | xargs cp -t /home/jh/Desktop/z",
" find . -name '*.bmp' | xargs cp -t /home/jh/Desktop/z",
" find . -name '*.tsx' | xargs cp -t /home/jh/Desktop/z",
" find . -name '*.tmx' | xargs cp -t /home/jh/Desktop/z",
" sudo apt install imagemagick",
" sudo apt-get install nautilus-image-converter",
" mogrify -resize 50% *.png",
" mogrify -resize 50% *.jpg",
" ls -la",
" mogrify -resize 50% *.jpg",
" mogrify -resize 50% *.png",
" mogrify -resize 50% *.bmp",
" mogrify -resize 20% *.jpg",
" mogrify -resize 20% *.png",
" cat '*.py > codemat.txt",
" cat *.py > codemat.txt",
" cd Downloads",
" cd",
" cd Downloads",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/u",
" cat *.py > codebigmat.txt",
" find . -name '*.py ' | xargs cp -t /home/jh/Desktop/u",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/u",
" mogrify -resize 20% *.png",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" wget --mirror --page-requisites --convert-links --adjus",
" mogrify -resize 30% *.png",
" mogrify -resize 40% *.png",
" mogrify -resize 20% *.png",
" mogrify -resize 50% *.png",
" mogrify -resize 20% *.png",
" mogrify -resize 40% *.png",
" mogrify -resize 30% *.png",
" mogrify -resize 10% *.png",
" cat *.py > rotatmotion01.txt",
" cat *.py > rotatmotion31.txt",
" cat *.py > turkey31.txt",
" cat *.py > wrapspritey31.txt",
" cat *.py > wexamples.txt",
" cat *.py > asidera1.txt",
" netstat -an | grep nfs.server.ip:port",
" netstat -an | grep nfs.server.192.168.5.104:2049",
" showmount -e 192.168.6.104",
" cat *.py > rotation_movement_all.txt",
" chmod -R 777",
" history",
" chmod 777 -R *.*",
" cd.",
" cd",
" cd Desktop",
" cd game projects",
" cd game_projects",
" chmod -R 777 *.*",
" apt-get install nfs-kernel-server",
" sudo apt-get install nfs-kernel-server",
" sudo apt autoremove",
" find data -name '*.py' -exec cat {} + > all.exe",
" find data -name '*.py' -exec cat {} + > all.txt",
" cd Downloads",
" cd",
" cd Downloads",
" find data -name '*.py' -exec cat {} + > alllll.txt",
" find -name '*.py' -exec cat {} + > alllll.txt",
" find -name '*.py' -exec cat {} + > ttttt.txt",
" chmod -R 777 *.*",
" cd",
" ifconfig",
" nmap 192.168.5.100/24",
" sudo nautilus",
" apt-get install nfs-kernel-server",
" sudo apt-get install nfs-kernel-server",
" sudo mkdir /mnt/myshareddir",
" find -name '*.py' -exec cat {} +> ttttt.txt",
" sudo ntfsfix sda",
" sudo apt-get install smartmontoo",
" sudo  fsck -a /dev/sda",
" e2fsck -b 32768 ./dev/sda",
" e2fsck -b 32768 /dev/sda",
" sudo e2fsck -b 32768 /dev/sda",
" sudo fdisk",
" sudo fdisk -l",
" chmod -R 777 *.*",
" chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" find -name '*.py' -exec cat {} + > alllll.txt",
" find -name '*.py' -exec cat {} > ttttt.txt",
" find -name '*.py' -exec cat {} +> ttttt.txt",
" find -name '*.py' -exec cat {} + > ttttt.txt",
" find -name '*.py' -exec cat {} + > advenb.txt",
" find data -name '*.py' -exec cat {} + > newcode.txt",
" sudo apt install nfs-common",
" mount -t nfs4 192.168.1.110:/media/nfs /media/share",
" ~mount -t nfs4 192.168.1.101:/media/nfs /nedia/share",
" mount -t nfs4 192.168.1.101:/media/nfs /nedia/share",
" export =a",
" export -a",
" systemctl start nfs",
" apt-get install nfs-kernel-server",
" sudo apt-get install nfs-kernel-server",
" sudo chmod 777 *.* -R",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/i",
" find data -name '*.py' -exec cat {} + > pygamecode.txt",
" find -name '*.py' -exec cat {} + > ttttt.txt",
" find -name '*.py' -exec cat {} + > fff.txt",
" find -name '*.py' -exec cat {} + > codeexamples.txt",
" find -name '*.py' -exec cat {} + > cod.txt",
" find -name '*.py' -exec cat {} + > ggg.txt",
" find -name '*.py' -exec cat {} + > newwcode.txt",
" find -name '*.py' -exec cat {} + > colision.txt",
" find -name '*.py' -exec cat {} + > asas.txt",
" find -name '*.py' -exec cat {} + > newdl.txt",
" sudo chmod 777 *.* -R",
" find -name '*.py' -exec cat {} + > GG.txt",
" find -name '*.py' -exec cat {} + > CHALLENGE.txt",
" find -name '*.py' -exec cat {} + > DXTOP.txt",
" sudo chmod 777 *.* -R",
" python -m black *.py",
" python -m black Desktop",
" sudo chmod 777 *.* -R",
" cd",
" cd Desktop",
" python -m black game_projects",
" sudo python -m black game_projects",
" sudo python3 -m black game_projects",
" cd",
" sudo python3 -m black Desktop/game_projects",
" python3 -m black Desktop/game_projects",
" sudo chmod 777 *.* -R",
" cd Desktop",
" cd.",
" cd..",
" cd",
" cd desktop",
" cd Desktop",
" python3 -m black Desktop/game_projects",
" python -m black /game_projects",
" python -m black game_projects",
" python -m black Downloads",
" cd Desktop",
" python -m black game_projects",
" sudo chmod 777 *.* -R",
" python -m black game_projects",
" python -m black [Desktop/game_projects]",
" python -m black 'h",
" python -m black -h",
" python -m black [Desktop]",
" python -m black Desktop",
" sudo chmod 777 *.* -R",
" cd jh",
" cd media",
" cd."
" cd./",
" cd ./",
" python -m black Python_Backup",
" sudo chmod 777 *.* -R",
" ls -la",
" sudo chmod 777 *.* -R",
" python -m black Desktop",
" python -m black \Desktop",
" find -name '*.py' -exec cat {} + > dungeoneer.txt",
" sudo chmod 777 *.* -R",
" 2to3 --output-dir=python3-version/rotatiom -W -n python",
" 2to3 --output-dir=python3-version/rotatiom -W -n python",
" 2to3 --output-dir=python3-version/rotatiom -W -n /rot",
" 2to3 --output-dir=python3-version/rotatiom -W -n rot",
" 2to3 --output-dir=python3-version/rotatiom -W -n THANG",
" 2to3 --output-dir=python3-version/rotatiom -W -n d",
" 2to3 --output-dir=python3-version/rotatiom -W -n d",
" 2to3 --output-dir=python3-version/rotatiom -W -n u",
" 2to3 game_projects -n -w -o scripts3",
" 2to3 Desktop_older -n -w -o scripts3",
" sudo apt install 2to3",
" 2to3 --output-dir=python3-version/rotatiom -W -n Deskto",
" 2to3 --output-dir=python3-version/rotatiom -W -n~ tile_",
" 2to3 --output-dir=fix -W -n~ tile_map_prg",
" 2to3 --output-dir=python3-version/rotatiom -W -n~ tile_",
" 2to3 --output-dir=python3-version/rotatiom -W -n~ *.*",
" 2to3 --output-dir=python3-version/rotatiom -W -n~ mv",
" $ 2to3 --output-dir=python3-version/mycode -W -n mv",
" 2to3 --output-dir=python3-version/mycode -W -n mv",
" 2to3 --output-dir=python3-version/mycode -W -n Download",
" history",
" 2to3 --output-dir=python3-version/mycode -W -n h",
" 2to3 --output-dir=python3-version/mycode -W -n Download",
" mogrify -resize 20% *.png",
" $ 2to3 --output-dir=tile_map_prg /mycode -W -n mv",
" 2to3 --output-dir=tile_map_prg /mycode -W -n mv",
" 2to3 --output-dir=tile_map_prg /mycode -W -n",
" 2to3 --output-dir=tile_map_prg / -W -n",
" 2to3 --output-dir=tile_map_prg /mapa_editor.py -W -n",
" 2to3 --output-dir=tile_map_prg /tile_map_prg -W -n",
" 2to3 --output-dir=tile_map_prg game_projects/tile_map_p",
" 2to3 --output-dir=tile_map_prg /*.py -W -n",
" 2to3 --output-dir=tile_map_prg /home/jh/Desktop/game_pr",
" 2to3 --output-dir=tile_map_prg /mapa_editor.py -W -n",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" mogrify -resize 20% *.png",
" mogrify -resize 20% *.JPG",
" mogrify -resize 20% *.jpg",
" sudo chmod 777 *.* -R",
" sudo thunar",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/png",
" find . -name ""*.png"" | xargs cp -t /home/jh/Desktop/png",
" find . -name *.png | xargs cp -t /home/jh/Desktop/png_f",
" cp -R *.png / /Desktop/png_folder",
" cp -R *.png / home/jh/Desktop/png_folder",
" cp -R *.png / /home/jh/Desktop/png_folder",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" nmap 192.168.5.101/24",
" cp -R *.png / /home/jh/Desktop/png_folder",
" cp -R home/jh/*.png /home/jh/Desktop/png_folder",
" cp -R /home/jh/*.png /home/jh/Desktop/png_folder",
" cp -R /home/jh/Downloads/*.png /home/jh/Desktop/png",
" cp -R /home/jh/*.png /home/jh/Desktop/png",
" sudo chmod 777 *.* -r",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" wget -r -A.avif http://https://unsplash.com/s/photos/hi",
" wget -r -A.avif http://https://unsplash.com/s/photos/hi",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" wine",
" wine config",
" sudo chmod 777 *.* -R",
" sudo chmod 777 *.* -R",
" display",
" calibre",
" sudo -v && wget -nv -O- https://download.calibre-ebook.",
" calibre",
" Console-Launcher.exe",
" 2to3",
" 2to3 mainwindow.py",
" cat *.py > CODE.TXT",
" cat *.py > gui_com.txt",
" sudo chmod 777 *.* -R",
" sudo chmod 777  -R",
" pycharm",
" 2323y",
" pycharm",
" pycharm.sh",
" ./pycharm.sh",
" sudo chmod 777",
" sudo chmod 777  -R",
" sudo chmod 777 *.* -R",
" ebook-convert myfile.epub myfile.pdf --enable-heuristic",
" You can also do the conversion from the Calibre GUI.",
" YOU CAN SUPPORT OUR WORK WITH A CUP OF COFFEE",
" As we continue to grow""ct mo",
" Thank You for your support as we work to give you the b",
" PayPal Support",
" Previous article",
" How To Install PHP 8.0 on Fedora 36/35/34/33/32",
" Next article",
" Install Android Studio on Ubuntu 22.04|20.04|18.04",
" Josphat Mutai",
" https://computingforgeeks.com/",
" Founder of Computingforgeeks. Expertise in Virtualizati",
" RELATED ARTICLESMORE FROM AUTHOR",
" PDF",
" Top 3 Best PDF to Word Converter Tools 2021 Free Downlo",
" Hacks",
" Download online web pages as PDF with Percollate",
" 2 COMMENTS",
" LEAVE A REPLY",
" Save my name"" and website in this browser for th""e nex"
" Recent Posts",
" View and Analyze Kubernetes API Traffic using Kubeshark",
" Modified date: December 18",
" Install vSphere 8.0 – vCenter Server Appliance using Li",
" Modified date: December 18",
" MQL: 4 Tips for Building Bots & Trading for Profit",
" Modified date: December 15",
" How to Become a PC Gamer (Complete Guide)",
" Modified date: December 15",
" Install VMware vSphere ESXi 8.0 on Bare-Metal Servers",
" Modified date: December 18",
" 10 Best 5G Phones to Buy in 2023",
" Modified date: December 15",
" Sergey Tokarev from Roosh talks about the challenges of",
" Modified date: December 15",
" Using Proxies to Generate Better Results in Advanced Da",
" Modified date: December 15",
" Electronics",
" Doogee S98 Set To Launch On March 28th With A Fresh...",
" Modified date: March 18",
" Best Laptop / Desktop Computer Monitors to Buy Under $2",
" Modified date: October 14",
" Cheaper Ink for HP Printers – Key Things to Know",
" Modified date: December 23",
" Doogee S98 Is Officially Opened For Preorders With Mass",
" Modified date: March 28",
" Dell vs Lenovo: Which Is Better And Why?",
" Modified date: October 27",
" Doogee’s First Tablet T10 Will Refresh You With Ultimat",
" Modified date: October 31",
" 5 Best Laptops For Design Students 2022",
" Modified date: January 1",
" Doogee S98 Is Expected To Launch With Dual-Screen & Nig",
" Modified date: March 2",
" 10 Best Noise Cancelling Headphones to buy 2022",
" Modified date: October 28",
" Doogee S89 Series – The Rugged Phone Series With 12000m",
" Modified date: August 10",
" ebook-convert 1000 Examples Programming In Python.epub",
" ebook-convert 100Python.epub myfile.pdf --enable-heuris",
" ebook-convert 1000 Examples Programming In Python.epub",
" ;//lp\==",
" find . -name '*.jpg' | xargs cp -t tempL/",
" find . -name '*.png' | xargs cp -t tempL/",
" find /Downloads/ -type f -name ""*.png"" -exec cp {} new-",
" find/home/jh /Downloads/ -type f -name ""*.png"" -exec cp",
" find /tempL/ -name ""*.jpg"" |  xargs  -I  '{}' cp {} /te",
" find -name ""*.jpg"" |  xargs  -I  '{}' cp {} /tempL/;~",
" cp -R home/jh/Downloads/ *.png /home/jh/Downloads/tempL",
" cp -R home/jh/Downloads/ *.png /home/jh/Downloads/tempL",
" cp -R /Downloads/ *.png /home/jh/Downloads/tempL",
" cp -R /Downloads/ *.png Downloads/tempL",
" systemctl --user mask tracker-store.service tracker-min",
" tracker3 reset -s -r",
" tracker reset --hard",
" cat *.py > min_examples1.txt",
" history",
" cat *.py > data_structures.txt",
" cp -R /Downloads/ *.png Downloads/png",
" cp -R jh/Downloads/ *.png  jh/Downloads/png",
" cp -R jh/Downloads/ *.png /Downloads/png",
" cp -R jh/Downloads/ *.png  /Downloads/png",
" cp -R jh/Downloads/ *.png  /Downloads/",
" cp -R /Downloads/ *.png /home/jh/Downloads/tempL",
" cp -R Downloads/ *.png /home/jh/Downloads/tempL",
" cp -R home/jh/Downloads/ *.png /home/jh/Downloads/png",
" ./p.bin",
" python -m nuitka p.py~",
" python -m nuitka p.py~",
" python -m nuitka p.py",
" python -m nuitka main.py",
" ./p.bin",
" python -m nuitka img.py",
" python -m nuitka main.py",
" chmod $777",
" sudo chmod $ 777 *.*",
" python -m nuitka sb.py",
" ./sb.bin",
" chmod 777",
" chmod 777 *.*",
" ls -la",
" chmod 777 v40",
" sudo ./img.bin",
" sudo./img.bin",
" ls -la",
" /media/jh/08DB-3B2E/py/.sb.bin",
" ls -la",
" /media/jh/08DB-3B2E/py/sb.bin",
" sudo /media/jh/08DB-3B2E/py/.sb.bin",
" ./img.bin",
" chmod 777 py",
" python -m nuitka SUPERBUTTON_CALCV3.30.py",
" python -m nuitka img.py",
" python -m nuitka main.py",
" python -m nuitka calc.py",
" sudo chmod 777 -R cpy",
" chmod 777 cpy",
" sudo chmod 777 -R calc",
" sudo chmod 777 -R img",
" sudo chmod 777 -R v40",
" ls -la",
" ./calc.bin",
" sudo chmod 777 -R cpy",
" ./p.bin",
" ./calc.sh",
" cat *.py > gui_com.txt",
" cat *.py > data_structures.txt",
" cat *.py > codea_structures.txt",
" find data -name '*.py' -exec cat {} + > all.txt",
" find -name '*.py' -exec cat {} + > all.txt",
" sudo chmod 777 -R cpy",
" cd",
" sudo chmod 777 -R cpy",
" cd Desktop",
" cd desktopfolders",
" sudo chmod 777 -R cpy",
" ./calc",
" ./calc.bin",
" sudo chmod 777 -R cpy",
" sudo chmod 777 -R",
" sudo chmod 777 -R calc",
" sudo chmod 777 -R img",
" ./calc.bin",
" sudo chmod 777 -R img",
" sudo chmod 777 -R calc",
" ls -la",
" sudo chmod 777 -R calc.bin",
" sudo chmod 777 -R calc.sh",
" sudo chmod 777 -R calc.build",
" sudo chmod 777 -R image_browser.py",
" ./img.bin",
" sudo chmod 777 -R img.build",
" sudo chmod 777 -R img.bin",
" sudo chmod 777 -R img.py",
" sudo chmod 777 -R image_broswer.py",
" ls -la",
" ./img.bin",
" ./calc.bin",
" sudo chmod 777 -R calc",
" sudo chmod 777 -R img",
" sudo chmod 777 -R calc.bin",
" ls -la",
" ./img.bin",
" find data -name '*.py' -exec cat {} + > Games_to_study.",
" find data -name '*.py' -exec cat {} + > Games_to_study2",
" find -name '*.py' -exec cat {} + > Games_to_study2.txt",
" find -name '*.py' -exec cat {} + > dundeoneer.txt",
" find -name '*.py' -exec cat {} + > Games_to_study.txt",
" history",
" rsync -a /home/jh/Desktop/desktopfolders/GAME /media/jh",
" 3@##",
" sudo apt-get update",
" sudo apt-get install -y build-essential ccache git zlib",
" sudo dpkg --add-architecture i386",
" rsync rsync -av /home/jh/Desktop/desktopfolders/GAME /m",
" history",
" ./calc.bin",
" ./calc.sh",
" sudo chmod 777 -R cpy",
" cd..",
" cd.",
" cd..",
" sudo chmod 777 -R cpy",
" sudo chmod 777 -R cpy",
" sudo chmod 777 -R img.sh",
" sudo chmod 777 -R img.sh",
" rsync rsync -av /home/jh/Desktop/desktopfolders/Desktop",
" rsync rsync --ignore-existing -av /home/jh/Desktop/desk",
" history",
" mogrify -resize 500% *.png",
" mogrify -path resize -resize 500% *.png",
" find -name '*.py' -exec cat {} + > EXAMPLPY1.txt",
" find -name '*.py' -exec cat {} + > EXAMPLE2.txt",
" find -name '*.py' -exec cat {} + > EXAMPLE4.txt",
" find -name '*.py' -exec cat {} + > omg_py4.txt",
" find -name '*.py' -exec cat {} + > EXAMPLE3.txt",
" mogrify -path size -resize 500% *.png",
" ./calc",
" mogrify -path size -resize 500% *.png",
" mogrify -path resize -resize 500% *.png",
" mogrify -path size -resize 500% *.png",
" mogrify -path size -resize 500% *.png",
" sudo chmod 777 -R *.*",
" mogrify -path size -resize 500% *.png",
" mogrify -resize 500% *.png",
" mogrify -path size -resize 500% *.png",
" SUDO APT INSTALL UPDATE",
" CD /MEDIA/JH/pYTHON_bACKUP",
" PWD",
" FIND . -NAME '*.PY' | XARGS CP -T /HOME/JH/dESKTOP/pydu",
" sudo apt install update",
" find -name '*.py' -exec cat {} + > EXAMPLE3.txt",
" find -name '*.py' -exec cat {} + > EXAMPLE4.txt",
" sudo chmod 777 -R calc",
" sudo chmod 777 -R *.*",
" cd /home/jh/Desktop/New folder",
" find -name '*.py' -exec cat {} + > EXAMPLE4.txt",
" cd Desktop",
" cd dd",
" find -name '*.py' -exec cat {} + > gui01.txt",
" cd ..",
" cd Desktop",
" cd jh",
" cd Desktop",
" cd d",
" find -name '*.py' -exec cat {} + > gui02.txt",
" cd Desktop",
" cd dd",
" find -name '*.py' -exec cat {} + > gui04.txt",
" cd.",
" cd..",
" cd/",
" cd",
" cd Desktop",
" cd gui",
" find -name '*.py' -exec cat {} + > gui05.txt",
" cd Dsektop",
" cd Desktop",
" sudo chmod 777 -R *.*",
" cd home/jh/Desktop/WALKING SPRITES",
" mogrify -path resized -resize 800% *.png",
" find -name '*.py' -exec cat {} + > pycode1.txt",
" find -name '*.py' -exec cat {} + > pycode1.txt",
" set -x;  D=firefox-browser.desktop; A=/usr/share/applic",
" find -name '*.py' -exec cat {} + > pygamecode1.txt",
" sudo snap install atom --classic",
" sudo apt-get install atom",
" find -name '*.py' -exec cat {} + > gamecode_refactore.t",
" FIND . -NAME '*.PY' | XARGS CP -T /HOME/JH/dESKTOP/I",
" find - name '*.py' | xargs cp -t /home/jh/Desktop/I",
" find - name '*.py' | xargs cp -t /I",
" find - name '*.py' | xargs cp -t /i",
" cp -R *.py /I",
" cp -R *.py /p",
" cp -R *.py p",
" find /home/jh/Desktop/info and snips -type f -name ""*.p",
" find /home/jh/Desktop/info and snips -type f -name ""*.p",
" CD",
" cd.",
" cd..",
" cd Desktop",
" ls -la",
" cd ..",
" find /home/jh/Desktop/info and snips -type f -name ""*.p",
" find /home/jh/Desktop/snips -type f -name ""*.py"" -exec",
" find /home/jh/Downloads -type f -name ""*.png"" -exec mv",
" find /home/jh/Downloads -type f -name ""*.png"" -exec mv",
" find /home/jh/Downloads -type f -name ""*.png"" -exec cp",
" sudo task manager",
" sudo xfce4-taskmanager",
" find /home/jh/Pictures/dated  -type f -name ""*.png"" -ex",
" find /home/jh/Pictures/dated -type f -name .png",
" find . -type f -name ""*.jpg"" -o -name ""*.png"" -o -name"
" find /home/jh/Pictures/dated -name ""*.jpg"" -o -name ""*."
" find /home/jh/Pictures/dated -name ""*.jpg"" -o -name ""*."
" find /home/jh/Pictures/dated -name ""*.jpg"" -o -name ""*."
" find /home/jh/Pictures/dated -name ""*.jpg"" -o -name ""*."
"Install PyInstaller: Open a terminal or command pro",
" pyinstaller --onefile game.py",
" pyinstaller -- version~",
" sudo apt-get update",
" sudo apt-get install pyinstaller",
" pyinstaller --onefile game.py",
" python -m pyinstaller --onefile game.py",
" python -m pyinstaller.py --onefile game.py",
" python -m pyinstaller --onefile game.py",
" python -m py_compile game.py",
" python -m compileall ./",
" nuitka game.py",
" nuitka3 game.py",
" ./game",
" ./game.bin",
" python -m nuitka --follow-imports game.py",
" python -m nuitka",
" python -m nuitka --follow-imports game.py",
" nuitka --follow-imports game.py",
" python -m nuitka --standalone --follow-imports game.py",
" python -m nuitka --standalone game.py",
" python -m nuitka --onefile game.py",
" python -m nuitka --standalone --module  game.py",
" python -m nuitka --module  game.py",
" gcc -o mystic module.game.c",
" python -m nuitka --help",
" sudo umount dev/sda1",
" sudo ntfsfix /dev/sda1",
" sudo chmod 777 -R *.*",
" pythom -m 2to3 main.py",
" python -m 2to3 main.py",
" python -m black /home/jh/Desktop/new OOP widgets/*.*",
" python -m black home/jh/Desktop/new OOP widgets/*.*",
" python -m black home/jh/Desktop/newOOPwidgets/*.*",
" python -m black /home/jh/Desktop/newOOPwidgets/*.*",
" python -m black /media/jh/Python_Backup/Space_Game/*.py",
" python -m black /home/jh/Desktop/GAME/*.py",
" python -m black /home/jh/Desktop/GAME/Sprite_Fronteerv4",
" python -m black /home/jh/Desktop/Camera_RPGsprite/*.py",
" python -m black /home/jh/Desktop/MYSTIC_v3/*.py",
" find / -type f | while read in ; do if file -i ""${in}""",
" sudo apt-get install python-gtk2-dev",
" sudo apt-get linux-gpib",
" history",
" cd gpt-engineer-project",
" cd /home/jh/gpt-engineer-project/env/bin",
" ls la",
" ls -la",
" python -m venv .venv && source .venv/bin/activate",
" git clone https://github.com/openai/openai-quickstart-n",
" npm run dev",
" mkdir gpt-engineer-project",
" cd gpt-engineer-project",
" source env/bin/activate",
" cd openai-quickstart-node",
" cp .env.example .env",
" npm install",
" sudo apt install npm",
" npm run dev",
" history",
" mogrify -path size -resize 50% *.png",
" history",
" wget -r -P /home/jh/websites https://web.archive.org/we",
" wget -r -P /home/jh/websites https://web.archive.org/we",
" wget -r -P /home/jh/websites https://web.archive.org/we",
" wget -r -P /home/jh/websites https://web.archive.org/we",
" wget -r -P /home/jh/websites https://web.archive.org/we",
" wget -r -P /home/jh/websites https://www.gameflare.com/",
" /bin/python /home/jh/absorberuu.py",
" source /home/jh/gpt-engineer-project/.venv/bin/activate",
" /home/jh/gpt-engineer-project/.venv/bin/python /home/jh",
" /home/jh/gpt-engineer-project/.venv/bin/python /home/jh",
" source /home/jh/gpt-engineer-project/.venv/bin/activate",
" https://github.com/AntonOsika/gpt-engineer.git",
" sudo apt install git-all",
" https://github.com/AntonOsika/gpt-engineer.git",
" /bin/python ""/home/jh/gpt-engineer-project/env/gptengin",
" nano ~/.bashrc",
" history",
" /bin/python ""/home/jh/gpt-engineer-project/env/gptengin",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" cd gpt-engineer",
" cd..",
" cd.",
" cd",
" cd gpt-engineer",
" mkdir test_app",
" cd test_app",
" touch main_prompt",
" python3 main.py test_app/",
" ll",
" cd",
" cd gpt-engineer",
" ll",
" python3 main.py test_app/",
" python3 main.py test_app/",
" python3 main.py test_app/",
" git clone https://github.com/AntonOsika/gpt-engineer.gi",
" cd gpt-engineer/",
" cp gpt_engineer/main.py",
" mv gpt_engineer/main.py",
" export OPEN_API_KEY= 87nOPcZQzQOwPWKI1ghoT3BlbkFJMTlyfk",
" export OPEN_API_KEY= sk-87nOPcZQzQOwPWKI1ghoT3BlbkFJMTl",
" Authorization: Bearer OPENAI_API_KEY",
" export  sk-87nOPcZQzQOwPWKI1ghoT3BlbkFJMTlyfklwcvYv8jEi",
" export sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW8Wp1TXzvfzjDsVj",
" export OPEN_API_KEY =sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW8",
" python3 main.py test_app/",
" python3 main.py projects/",
" export OPEN_API_KEY =sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW8",
" export sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW8Wp1TXzvfzjDsVj",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py projects/",
" cd gpt_engineer",
" python3 main.py projects/",
" ll",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" import tkinter as tk",
" from tkinter import ttk",
" from PyPDF2 import PdfFileReader",
" class PDFViewer(tk.Frame):",
" export OPEN_API_KEY= 87nOPcZQzQOwPWKI1ghoT3BlbkFJMTlyfk",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" export OPENAI_API_KEY=sk-zBFJL3QvRFw9vLQNW7gkT3BlbkFJAW",
" python3 main.py test_app/",
" mogrify -path size -resize 50% *.png",
" mogrify -path size -resize 50% *f.png",
" mkdir m",
" mogrify -path size -resize 50% *f.png /m",
" mogrify -path size -resize 50% /m *.png",
" mogrify -path size -resize 50% *.png",
" git clone git@github.com:mortoray/path-finding.git",
" sudo apt-get install gnash",
" ./VentoyGUI.x86_64",
" cd /home/jh/Downloads/ventoy-1.0.96-linux/ventoy-1.0.96",
" ./VentoyGUI.x86_64",
" ./VentoyWeb.sh",
" sudo VentoyWeb.sh",
" ./sudo VentoyWeb.sh",
" ./VentoyWeb.sh",
" ./VentoyGUI.x86_64",
" ./horoscope.sh",
" pwd",
" ./horoscope.sh",
" ./horoscope.sh",
" python -m nuitka --onefile --noconsole horoscope2.py",
" python -m nuitka --onefile horoscope2.py",
" python -m nuitka linux-onefile-icon horoscope2.py",
" python -m nuitka  --linux-onefile-icon=ICON_PATH horosc",
" python -m nuitka  --linux-onefile-icon=/usr/share/icons",
" dmesg | tail",
" lsblk",
" fdick -l",
" fdisk -l",
" sudo fdisk -l",
" sudo mkdir /mnt/mydrive",
" sudo mount /dev/sda /mnt/mydrive",
" sudo ntfsfix /dev/sda",
" sudo fsck.vfat -r /dev/sda",
" sudo umount /dev/sda",
" sudo fsck -a /dev/sda",
" e2sck -b 32768",
" sudo fsck -f /dev/sda",
" sudo apt-get install ntfs-3g ntfsprogs",
" sudo mkdir /mnt/ntfs",
" sudo mount -t ntfs /dev/sda /mnt/ntfs",
" sudo mount -t ntfs /dev/sda1 /mnt/ntfs",
" sudo ntfsfix /dev/sda1",
" history > history_output.txt",
" history > history_output4.txt",
" history -> historynew.txt",
" pyinstaller --onefile --noconsole horoscope_oop.py",
" sudo apt update && sudo apt upgrade -y",
" ./configure --prefix=/usr/local --enable-optimizations",
" make -j $(nproc)",
" make -j 12",
" sudo make altinstall",
" python3.12 -V",
" dpkg --get-selections | grep python",
" dpkg --get-selections | grep python",
" dpkg --get-selections | grep python3.12",
" sudo apt-get install tk",
" make idle",
" python3.12 -m idlelib",
" sudo apt-get install tk-dev tcl-dev",
" make",
" sudo apt-key list",
" sudo chmod 777 /",
" sudo blkid",
" sudo nano /etc/fstab",
" sudo blkid",
" sudo mount /dev/sdb /mnt/drv1.8tb",
" sudo mkdir /mnt/drv1.8tb",
" sudo mount /dev/sdb /mnt/drv1.8tb",
" sudo gedit /etc/fstab",
" sudo chmod 777 /mnt/drv1.8tb",
" sudo umount /mnt/drv1.8tb",
" sudo mount /mnt/drv1.8tb",
" wsudo gedit /etc/fstab",
" sudo gedit /etc/fstab",
" sudo mount /mnt/drv1.8tb",
" sudo gedit /etc/fstab",
" sudo chmod 777 /media/jh/1.8TB/",
" chmod 777 -R /Desktop/pics",
" sudo chmod 777 /Desktop/pics",
" sudo chmod 777 _R /home/jh/Desktop/pics/",
" sudo ntfsfix sdb1",
" sudo fdisk -l",
" mount sdb",
" sudo ntfsfix sdb1",
" sudo ntfsfix sdb",
" sudo fsck -a /dev/sdb",
" esfsck -b sdb",
" sudo apt install e2fsck",
" sudo fsck /dev/sdb",
" Yesterday",
" sudo chown",
" chown -help",
" ./chgper.sh",
" sudo ./chgper.sh",
" sudo blkid",
" sudo gedit /etc/fstab",
" sudo chmod 777 /mnt/pybak",
" sudo gedit /etc/fstab",
" sudo chmod 777 /mnt/pybak",
" cd /mnt/pybak",
" mkdir /mnt/pybak",
" sudo mkdir /mnt/pybak",
" sudo mount /mnt/pybak",
" sudo mount -t ext4 /dev/sdb1 /mnt/pybak",
" sudo fsck.ext4 -f /dev/sdb1",
" sudo chmod 777 /mnt/pybak",
" sudo umount /mnt/pybak",
" sudo mount /mnt/pybak",
" sudo gedit /etc/fstab",
" sudo mount /mnt/pybak",
" sudo chmod 777 /mnt/pybak",
" sudo mount /mnt/pybak",
" cd Desktop",
" history",
]
cmditem = [  "sudo thunar",
" find . -name '*.jpg' | xargs cp -t /media/jh/Python_Bac",
" cd",
" find . -name '*.jpg' | xargs cp -t /media/jh/Python_Bac",
" find . -name '*.py' | xargs cp -t /media/jh/Python_Back",
" find . -name '*.py' | xargs cp -t /a",
" find . -name '*.py' | xargs cp -t a",
" find . -name 'tkgui.py' | xargs cp -t/media/jh/Python_B",
" find . -name 'tkgu*.py' | xargs cp -t/media/jh/Python_B",
" find . -name 'tkguigen.py' | xargs cp -t b",
" find . -name 'tkgui*.py ' | xargs cp -t b",
" pip install Nuitka",
" sudo pip install cython",
" cd Desktop",
" python -m nuitka --standalone jhapp.py",
" python -m nuitka --standalone ==plugin-enable=tk-inter",
" python -m nuitka --standalone --plugin-enable=tk-inter",
" python -m nuitka --onefile --plugin-enable=tk-inter jha",
" python -m nuitka --standalone ==plugin-enable=tk-inter",
" python -m nuitka --standalone --plugin-enable=tk-inter",
" pip install cx-Freeze",
" cmake",
" ./configure",
" make",
" gcc MainProgrm.c",
" gcc /usr/lib/python3/dist-packages/nuitka/build/static_",
" gcc source.c",
" python -m nuitka --onefile jhapp.py",
" history",
" sudo apt install update",
" find . -name 'tt.pp' | xargs cp -t /home/jh/Desktop/d",
" pip install PySimpleGUI",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" cd Downloads",
" pwd",
" cd Downloads",
" pwd",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" find . -name 'image*.py'",
" find . -name 'image*.py'> search.txt",
" pip install webview",
" cd",
" pwd",
" find . -name '*.jpg"" *.gif' | xargs cp -t /home/""jh/De"
" cd",
" pwd",
" find . -name '*.jpg"" *.gif'| xargs cp -t /home/j""h/Des"
" cd",
" pwd",
" find . -name '*.jpg' | xargs cp -t /home/jh/Desktop/All",
" cd /media/jh/Python_Backup",
" pwd",
" cd /media/jh/Python_Backup",
" pwd",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" cd /media/jh/Python_Backup",
" pwd",
" find . -name '*.py' | xargs cp -t /home/jh/Desktop/PYDU",
" pip installgeocoder~",
" pip install geocoder",
" history",
" ifconfig",
" sudo nmap -sP 192.168.1.0/24",
" sudo nmap -sP 192.168.5.0/24",
" sudo apt-get install nmap",
" sudo nmap 192.168.5.0/255",
" sudo nmap 192.168.5.0/115",
" ifconfig",
" mount nfs",
" sudo nmap -sP 192.168.5.0/24",
" pip install pyttsx3",
" pip install speech_recognition",
" pip install speechrecognition",
" pip install wolframalpha",
" fdfdfdfdsdgdfdf",
" pip install pytesseract",
" sudo apt-get update",
" sudo apt-get install tesseract-ocr",
" pip install pygubu-designer",
" pygubu-designer",
" python3 -m pygubu-designer",
" cd /usr",
" cd..",
" cd  /.local/lib/python3.9/site-packages",
" cd .local/lib/python3.9/site-packages",
" cd",
" cd .local/lib/python3.9/site-packages",
" ;a -la",
" ls =la",
" ls -la",
" pygubu",
" pygubudesigner",
" pygubu_designer",
" cd .local/lib/python3.9/site-packages",
" pygubu_designer",
" cd .local/lib/python3.9/site-packages",
" cd  /.local/lib/python3.9/site-packages",
" pygubu_designer",
" sudo nmap 192.168.5.0/115",
" sudo nmap 192.168.5.101/24",
" cd Desktop",
" fastboot flash cust-unlock <unlock_token.bin>",
" ~",
" fastboot flash cust-unlock <unlock_token.bin>",
" fastboot oem unlock",
" sudo adb devices",
" fastboot oem unlock",
" fastboot flash cust-unlock <unlock_token.bin>",
" unlock_token.bin",
" ls -la",
" fastboot flash cust-unlock unlock_code.bin~",
" fastboot flash cust-unlock unlock_code.bin",
" fastboot oem  unlock",
" fastboot boot twrp.img",
" sudo adb devices",
" adb reboot bootloader",
" fastboot boot twrp.img",
" fastboot devices",
" fastboot boot twrp.img",
" adb sideload twrp_perm.zip",
" fastboot boot twrp_perm.img",
" fastboot devices",
" adb reboot bootloader",
" fastboot devices",
" fastboot boot twrp_perm.img",
" cd Desktop",
" sudo adb devices",
" sudo apt-get install android-tools-adb",
" sudo adb devices",
" adb devices",
" fastboot flash cust-unlock <unlock_token.bin>",
" fastboot oem unlock",
" fastboot flash cust-unlock <unlock_token.bin>",
" dir",
" cd Downloads",
" adb reboot bootloader",
" fastboot devices",
" fastboot oem unlock",
" adb reboot bootloader",
" fastboot oem unlock",
" fastboot flash boot RECOVERY.img",
" adb reboot bootloader",
" abd sideload LINEAGE.zip",
" sudo adb sideload LINEAGE.zip",
" adb devices",
" pip3 install -r requirements.txt",
" pip install pydirectinput",
" pip3 install -r requirements.txt",
" pip3 install geoplot",
" find . -name '*.png' | xargs cp -t /home/jh/Desktop/png",
" pip3 install -r requirements.txt",
" find . -name 'calc*.py' | xargs cp -t /home/jh/Desktop/",
" find . -name 'cal*.py' | xargs cp -t /home/jh/Desktop/c",
" find . -name 'calc*.py' | xargs cp -t /home/jh/Desktop/",
" cp --help",
" find . -name 'calc*.py' | xargs cp -t /home/jh/Desktop/",
" find . -name 'cal*.py' | xargs cp -t /home/jh/Desktop/c",
" find . -name 'cal*.py' | xargs cp -r -t /home/jh/Deskto",
" sudo apt-get update",
" history",
" cal",
" finger user",
" whyiami",
" whoami",
" sudo nmap 192.168.5.0/115",
" sudo nmap 192.168.5.115/24",
" sudo apt install update",
" sudo apt-get install update",
" fastboot flash recovery twrp.img",
" fastboot devices",
" adb reboot bootloader",
" abd devices",
" adb devices",
" adb reboot bootloader",
" adb devices",
" adb reboot bootloader",
" fastboot boot twrp.img",
" sudo apt-get update",
" d2323",
" o",
" sudo apt-get update",
" uname",
" sudo dpkg --configure -a",
" sudo nmap 192.168.5.115/24",]
