r1 = ttk.(top)
r1.config(command = text1.insert(tk.END, a)) 
r1.grid(row=1,column=1)
r2 = ttk.(top)
r2.config(command = text2.insert(tk.END, a)) 
r2.grid(row=2 column=1)
r3 = ttk.(top)
r3.config(command = text3.insert(tk.END, a)) 
r3.grid(row=3 column=1)
r4 = ttk.(top)
r4.config(command = text4.insert(tk.END, a)) 
r4.grid(row4= column=1)()
r5 = ttk.(top)
r5.grid(row=5 column=1)
r5.config(command=text5.insert(tk.END, a)) 
