r1 = ttk.Radiobutton(fr1, text = 'save1', variable=1, value = 'Text Tab 1')
r1.config(command = select_save(1)
r2 = ttk.Radiobutton(fr1, text = 'save1', variable=2, value = 'Text Tab 1')
r2.config(command = select_save(2)
r3 = ttk.Radiobutton(fr1, text = 'save2', variable=3, value = 'Text Tab 2')
r3.config(command = select_save(3)
r4 = ttk.Radiobutton(fr1, text = 'save3', variable=4, value = 'Text Tab 3')
r4.config(command = select_save(4)
r5 = ttk.Radiobutton(fr1, text = 'save4', variable=5, value = 'Text Tab 4')
r5.config(command = select_save(5)
r6 = ttk.Radiobutton(fr1, text = 'save5', variable=6, value = 'Text Tab 5')
r6.config(command = select_save(6)
r7 = ttk.Radiobutton(fr1, text = 'save6', variable=7, value = 'Text Tab 6')
r7.config(command = select_save(7)
r8 = ttk.Radiobutton(fr1, text = 'save7', variable=8, value = 'Text Tab 7')
r8.config(command = select_save(8)
r9 = ttk.Radiobutton(fr1, text = 'save8', variable=9, value = 'Text Tab 8')
r9.config(command = select_save(9)
r10 = ttk.Radiobutton(fr1, text = 'save9', variable=10, value = 'Text Tab 9')
r10.config(command = select_save(10)
r11 = ttk.Radiobutton(fr1, text = 'save10', variable=11, value = 'Text Tab 10')
r11.config(command = select_save(11)


r1.grid(row=1, column=3)
r2.grid(row=2, column=3)
r3.grid(row=3, column=3)
r4.grid(row=4, column=3)
r5.grid(row=5, column=3)
r6.grid(row=6, column=3)
r7.grid(row=7, column=3)
r8.grid(row=8, column=3)
r9.grid(row=9, column=3)
r10.grid(row=10, column=3)
r11.grid(row=11, column=3)
